# Development Profile
spring.config.activate.on-profile=dev

# Database PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/rpg_fichas
spring.datasource.username=myuser
spring.datasource.password=secret

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
